name: Ripple
options:
  bundleIdPrefix: com.mattsilverman
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: false
targets:
  Ripple:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mattsilverman.ripple
        SWIFT_VERSION: 5.9
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        METAL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
